name: coursenotes-backend
version: '3'
services:
  backend:
    build: .
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/data
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  database:
    container_name: postgres-database
    image: postgres
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres